#!/bin/bash

# Install ufw if not already installed
sudo apt-get update
sudo apt-get -y install ufw

# Set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow incoming traffic on specific ports
sudo ufw allow 22/tcp     # SSH
sudo ufw allow 80/tcp     # HTTP
sudo ufw allow 443/tcp    # HTTPS SSL

# Enable ufw
sudo ufw enable

# Display status to verify rules
sudo ufw status
